# Generated by Django 5.0.2 on 2024-02-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
